version:
  1
handlers:
  console:
    class: logging.StreamHandler
    formatter: normal
    stream: ext://sys.stdout
    filters: [userid]
filters:
  userid:
    (): dexter.logs.userIdFilterFactory
    class: dexter.logs.UserIdFilter
formatters:
  normal:
    format: '%(asctime)s %(process)-6d %(name)-12s %(userid)s %(levelname)-8s %(message)s'
loggers:
  requests:
    level: DEBUG
  sqlalchemy.engine:
    level: INFO
  passlib:
    level: INFO
root:
  handlers: [console]
  level: DEBUG
